# Generated by Django 5.1 on 2025-05-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MUN_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='sessionName',
        ),
    ]
