# Generated by Django 5.2.8 on 2025-11-18 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN_APP', '0003_classsection_event_notice_userregistration_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUN_APP.classsection')),
            ],
        ),
    ]
