# Generated by Django 5.2.8 on 2025-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN_APP', '0004_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='phone',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
