# Generated by Django 5.2.8 on 2025-12-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN_APP', '0005_alter_userregistration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
