# Generated by Django 6.0.3 on 2026-03-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN_APP', '0006_feepayment_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Income Tax %')),
                ('pf_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='PF %')),
                ('leave_days', models.PositiveIntegerField(default=0, verbose_name='Leave days / year')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hra_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='HRA %')),
                ('da_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='DA %')),
                ('ta_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TA %')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent'), ('hm', 'Head Master'), ('accountant', 'Accountant')], default='parent', max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='MUN_APP.userregistration')),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MUN_APP.employeetype')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MUN_APP.payrollgrade')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('class_section', models.ForeignKey(blank=True, help_text='Leave blank for all classes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MUN_APP.classsection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('mid_term', 'Mid-Term'), ('final', 'Final Exam'), ('assignment', 'Assignment')], max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MUN_APP.userregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='MUN_APP.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='MUN_APP.subject')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
    ]
