# Generated by Django 6.0.3 on 2026-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN_APP', '0007_employeetype_payrollgrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_section',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='parent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent')], default='parent', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.DeleteModel(
            name='PayrollGrade',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
